# Generated by Django 6.0.2 on 2026-02-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_auth', '0002_scheduledtweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtweet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
